### PR TITLE
fix: change `cloudant.since` logic to prefer saved offset, if present

### LINKED ISSUE #124: `cloudant.since` defaults to 0 which means the connector always starts from the beginning on restarts
### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

- Create document in cloudant
- Start source connector
- Shut down connector
- Start source connector again

### 2. What you expected to happen

One event created on sink topic

### 3. What actually happened

Two events created on sink topic

## Environment details
main latest

### PR DESCRIPTION
**Pull request by tomblench**
fixes #124

### CODE REVIEW

**Review by ricellis — COMMENTED** [review]
The change seems fine, but I wonder if we should do three additional things here, namely:
1. Update https://github.com/IBM/cloudant-kafka-connector/blob/9c52db6926c53a3fde4a9f9d09f1b44c6ee9ae60/src/main/resources/message_en_US.properties#L46 to indicate what the behaviour is when unset (since it will no longer show a default value of `"0"` I think).
1. Regenerate the config doc since the default is now different (and to include above update).
1. Add a test so we don't accidentally regress this at some point.

**Comment by tomblench** [comment]
> The change seems fine, but I wonder if we should do three additional things here, namely:
> 
> 1. Update https://github.com/IBM/cloudant-kafka-connector/blob/9c52db6926c53a3fde4a9f9d09f1b44c6ee9ae60/src/main/resources/message_en_US.properties#L46
>     to indicate what the behaviour is when unset (since it will no longer show a default value of `"0"` I think).
> 2. Regenerate the config doc since the default is now different (and to include above update).
> 3. Add a test so we don't accidentally regress this at some point.

1. could you please look at 64386b41e34505d0eefa12795c2f44bc49551c99 - i'm not totally sure what the message should look like here so i'm open to suggestions (eg should it be more explicit that this behaviour is used to track the latest sequence between restarts)
2. sure
3. just a unit test for the defaults? that should be pretty easy

**Review by ricellis — APPROVED** [review]
+1, small nit

**Review by ricellis — APPROVED** [review]
+1 a couple of nits on copy/paste test comments

**Comment by tomblench** [comment]
thanks @ricellis for spotting those copy/pastes

**Pull request merged**
